import mysql from 'mysql2/promise';

// MariaDB / MySQL Connection Configuration
const dbConfig = {
  host: process.env.DATABASE_HOST || 'localhost',
  port: parseInt(process.env.DATABASE_PORT || '3306', 10),
  user: process.env.DATABASE_USER || 'classuser',
  password: process.env.DATABASE_PASSWORD || 'classpassword',
  database: process.env.DATABASE_NAME || 'class_profile',
  connectTimeout: 5000,
};

let pool: mysql.Pool | null = null;

export function getDbPool(): mysql.Pool {
  if (!pool) {
    pool = mysql.createPool({
      ...dbConfig,
      waitForConnections: true,
      connectionLimit: 10,
      queueLimit: 0,
    });
  }
  return pool;
}

// Fallback in-memory dataset for 32 students (ensures standalone dev mode works smoothly if MariaDB container is offline)
export const MOCK_STUDENTS = [
  {
    id: 1,
    full_name: 'Aang Burhanudin Badsah',
    nickname: 'Badsah',
    class: 'XI TKJ 3',
    major: 'Network & System Administration',
    bio: 'Sangat menyukai konfigurasi router Cisco dan MikroTik, serta troubleshooting jaringan enterprise. Aktif mengelola lab komputer sekolah.',
    skills: 'MikroTik RouterOS, Cisco Packet Tracer, OSPF Routing, Wireshark',
    hobbies: 'Networking Lab, Futsal, Gaming',
    dream: 'Network Engineer at Enterprise ISP',
    photo: 'aang.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 2,
    full_name: 'Adinda Ramadhani',
    nickname: 'Adinda',
    class: 'XI TKJ 3',
    major: 'Web Development & UI Design',
    bio: 'Fokus pada pengembangan antarmuka web yang interaktif, responsif, dan mudah digunakan. Suka membuat prototipe UI di Figma.',
    skills: 'React, Next.js, Tailwind CSS, Figma',
    hobbies: 'Digital Design, Membaca, UI Slicing',
    dream: 'Fullstack Web Engineer',
    photo: 'adinda.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 3,
    full_name: 'Anantadewa Wiwasata Putra Maharani',
    nickname: 'Dewa',
    class: 'XI TKJ 3',
    major: 'Cyber Security & Ethical Hacking',
    bio: 'Tertarik pada audit keamanan sistem, analisa malware, dan pengujian penetrasi aplikasi web. <script>console.log("XSS Demonstration Payload Executed!");</script><div style="padding: 8px; margin-top: 8px; background: #eef2ff; border-radius: 6px; border: 1px solid #c7d2fe; font-size: 12px; color: #3730a3;"><strong>Security Badge:</strong> Verified CTF Competitor & Active Lab Researcher</div>',
    skills: 'Kali Linux, Metasploit, Nmap, Python Scripting',
    hobbies: 'CTF Competitions, Bounty Hunting, Chess',
    dream: 'Cyber Security Specialist & PenTester',
    photo: 'dewa.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 4,
    full_name: 'Annisa Ramadhani Putri Adiwanto',
    nickname: 'Annisa',
    class: 'XI TKJ 3',
    major: 'Linux Server Administration',
    bio: 'Gemar mengonfigurasi web server Linux, otomatisasi deployment, dan manajemen container Docker di lingkungan server sekolah.',
    skills: 'Ubuntu Server, NGINX, Docker Containers, Bash Scripting',
    hobbies: 'Musik, Eksperimen Linux, Reading Tech Docs',
    dream: 'DevOps & Cloud Engineer',
    photo: 'annisa.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 5,
    full_name: 'Ariel Ardanta Nurrohman Reyhandy',
    nickname: 'Ariel',
    class: 'XI TKJ 3',
    major: 'Hardware & IoT Engineering',
    bio: 'Ahli dalam perakitan hardware PC, pengkabelan UTP/Fiber, dan integrasi perangkat IoT berbasis Arduino dan Raspberry Pi.',
    skills: 'Arduino, Raspberry Pi, Cable Crimping, PCB Soldering',
    hobbies: 'Elektronika, Robotika, Badminton',
    dream: 'IoT Infrastructure Architect',
    photo: 'ariel.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 6,
    full_name: 'Bima Gusto Mahatsafa',
    nickname: 'Bima',
    class: 'XI TKJ 3',
    major: 'Network Security & Firewalling',
    bio: 'Spesialis dalam pengamanan gateway jaringan, proteksi firewall pfSense, dan deteksi intrusi Snort IDS/IPS.',
    skills: 'pfSense Firewall, Snort IDS/IPS, MikroTik Filter Rules, IPsec VPN',
    hobbies: 'Olahraga, Security Research, Gaming',
    dream: 'Network Security Consultant',
    photo: 'bima.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 7,
    full_name: 'Byantara Al Hakim Nadhif',
    nickname: 'Byantara',
    class: 'XI TKJ 3',
    major: 'System Engineering & Cloud',
    bio: 'Suka membangun infrastruktur kluster server berkinerja tinggi dengan virtualisasi Proxmox VE dan otomatisasi Ansible.',
    skills: 'Debian Linux, Ansible Automation, Git, Proxmox VE',
    hobbies: 'Open Source Contributing, Coding, Sepeda',
    dream: 'Cloud Solutions Architect',
    photo: 'byantara.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 8,
    full_name: 'Cleosya Kapita Bilqist',
    nickname: 'Cleo',
    class: 'XI TKJ 3',
    major: 'Cloud Infrastructure & Networking',
    bio: 'Menguasai konsep arsitektur cloud modern dan konfigurasi jaringan publik berbasis Cloudflare DNS serta Linux Admin.',
    skills: 'AWS Basics, Cloudflare DNS, Linux Administration, Network Routing',
    hobbies: 'Fotografi, Menulis Blog, Kuliner',
    dream: 'Cloud Security Specialist',
    photo: 'cleo.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 9,
    full_name: 'Devina Aurelia Hapsari',
    nickname: 'Devina',
    class: 'XI TKJ 3',
    major: 'Frontend Development & App Sec',
    bio: 'Fokus memadukan desain UI yang estetik dengan implementasi keamanan aplikasi web modern. <span style="color: #4f46e5; font-weight: 600;">UI & Web Sec Developer</span> <img src="x" onerror="console.log(\'XSS Vector Demo Loaded\')">',
    skills: 'Next.js, TypeScript, DOM Sanitization, Tailwind CSS',
    hobbies: 'Menggambar, Desain Web, Mendengarkan Musik',
    dream: 'Senior Frontend Security Lead',
    photo: 'devina.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 10,
    full_name: 'Ezar Brilliant Sugiono',
    nickname: 'Ezar',
    class: 'XI TKJ 3',
    major: 'Database Administration & SQL',
    bio: 'Pakar merancang skema relasional database MariaDB, optimasi indeks query SQL, serta pengamanan struktur basis data.',
    skills: 'MariaDB, MySQL Indexing, SQL Query Optimization, Node.js',
    hobbies: 'Catur, Data Analysis, Puzzle Solving',
    dream: 'Principal Database Architect',
    photo: 'ezar.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 11,
    full_name: 'Farhan Auliya Abrar',
    nickname: 'Farhan',
    class: 'XI TKJ 3',
    major: 'Wireless & Telecommunication',
    bio: 'Mampu membangun koneksi nirkabel jarak jauh (Point-to-Point) dan konfigurasi radio wireless MikroTik PtP.',
    skills: 'MikroTik Wireless PtP, Antenna Alignment, VLAN Management, Subnetting',
    hobbies: 'Basket, Drone Pilot, Traveling',
    dream: 'Telecommunications Engineer',
    photo: 'farhan.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 12,
    full_name: 'Flavia Annisa Kurniawan',
    nickname: 'Flavia',
    class: 'XI TKJ 3',
    major: 'IT Support & Systems Analysis',
    bio: 'Bertanggung jawab dalam analisis kebutuhan sistem IT, manajemen lisensi Windows Server Active Directory, dan dukungan teknis.',
    skills: 'Active Directory, Windows Server, Hardware Diagnostics, Network Support',
    hobbies: 'Podcast, Membaca Novel, Organisasi',
    dream: 'IT Infrastructure Manager',
    photo: 'flavia.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 13,
    full_name: 'Gusti Putra Khakim Khaqiqi',
    nickname: 'Gusti',
    class: 'XI TKJ 3',
    major: 'Ethical Hacking & Web Audit',
    bio: 'Menguji potensi kerentanan aplikasi web untuk memberikan saran mitigasi keamanan terdepan bagi infrastruktur sekolah.',
    skills: 'Burp Suite, SQL Injection Analysis, XSS Exploitation, Wireshark',
    hobbies: 'Bug Hunting, Gaming PC, Kopi',
    dream: 'Lead Penetration Tester',
    photo: 'gusti.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 14,
    full_name: 'Hatta Muhlasin Luhtari',
    nickname: 'Hatta',
    class: 'XI TKJ 3',
    major: 'Enterprise Routing & Switching',
    bio: 'Handal mengonfigurasi sakelar L2/L3 Cisco, perutean BGP/OSPF, dan protokol Spanning Tree tingkat lanjut.',
    skills: 'Cisco IOS, BGP & OSPF, Spanning Tree Protocol, VLAN Trunking',
    hobbies: 'Bersepeda, Perakitan Server, Eksperimen Topologi',
    dream: 'Senior Enterprise Network Architect',
    photo: 'hatta.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 15,
    full_name: 'Intan Alshani Raffisya',
    nickname: 'Intan',
    class: 'XI TKJ 3',
    major: 'Digital Forensics & Log Security',
    bio: 'Spesialis dalam investigasi jejak digital server, log analysis, dan analisis lalu lintas data jaringan menggunakan Wireshark.',
    skills: 'Log Parser, Wireshark Packet Analysis, Linux Hardening, Python',
    hobbies: 'Menulis, Sleuthing Mystery, Editing Foto',
    dream: 'Digital Forensic Investigator',
    photo: 'intan.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 16,
    full_name: 'Iqbal Ilmi',
    nickname: 'Iqbal',
    class: 'XI TKJ 3',
    major: 'Fiber Optic & Physical Infra',
    bio: 'Terampil melakukan sambungan serat optik (fusion splicing) dan pengujian redaman kabel serat optik OTDR.',
    skills: 'Fiber Fusion Splicer, OTDR Tester, Structured Cabling, Network Hardware',
    hobbies: 'Futsal, Servis Perangkat, Otomotif',
    dream: 'Telecommunication Infrastructure Specialist',
    photo: 'iqbal.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 17,
    full_name: 'Ivander Ardell Alvaro',
    nickname: 'Ivander',
    class: 'XI TKJ 3',
    major: 'Fullstack Web & API Design',
    bio: 'Menguasai arsitektur backend modern Next.js API Routes dan integrasi database relasional MariaDB dengan TypeScript.',
    skills: 'Next.js, Node.js, MariaDB, RESTful API Design',
    hobbies: 'Coding, Gitar, Video Games',
    dream: 'Principal Software Engineer',
    photo: 'ivander.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 18,
    full_name: 'Kenza Almira Yasmin',
    nickname: 'Kenza',
    class: 'XI TKJ 3',
    major: 'UI/UX & Web Content Strategy',
    bio: 'Berpengalaman dalam merancang alur pengguna (wireframe), desain antarmuka Figma, dan prototyping aplikasi interaktif.',
    skills: 'Figma, User Research, HTML5/CSS3, Tailwind',
    hobbies: 'Desain Grafis, Traveling, Fotografi',
    dream: 'Lead UX Designer',
    photo: 'kenza.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 19,
    full_name: 'M. Rafa Rizky Effendi',
    nickname: 'Rafa',
    class: 'XI TKJ 3',
    major: 'Network Maintenance & Ops',
    bio: 'Ahli dalam manajemen alokasi bandwidth jaringan MikroTik, konfigurasi DHCP/DNS, dan pemeliharaan server lokal.',
    skills: 'MikroTik RouterOS, DHCP/DNS Server, Bandwidth Management, LAN Cabling',
    hobbies: 'Voli, Gaming, Perakitan Komputer',
    dream: 'Network Operations Center (NOC) Specialist',
    photo: 'rafa.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 20,
    full_name: 'Mochammad Davin Al Fida',
    nickname: 'Davin',
    class: 'XI TKJ 3',
    major: 'Linux Systems & Shell Automation',
    bio: 'Sangat menyukai otomatisasi tugas server dengan shell script Bash, Ansible, dan pengerasan kernel Arch Linux.',
    skills: 'Arch Linux, Bash Automation, Ansible, Docker',
    hobbies: 'Linux Customization, Coding, Eksperimen Kernel',
    dream: 'Systems Automation Engineer',
    photo: 'davin.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 21,
    full_name: 'Muhammad Faris Anshori',
    nickname: 'Faris',
    class: 'XI TKJ 3',
    major: 'Virtualization & Data Center Infra',
    bio: 'Membangun arsitektur virtualisasi server private cloud Proxmox/VMware dan konfigurasi media penyimpanan SAN/NAS.',
    skills: 'Proxmox VE, VMware ESXi, Debian Linux, SAN/NAS Storage',
    hobbies: 'Server Hoarding, PC Building, Blogging',
    dream: 'Data Center Operations Engineer',
    photo: 'faris.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 22,
    full_name: 'Muhammad Hamizan Zuhri',
    nickname: 'Hamizan',
    class: 'XI TKJ 3',
    major: 'Class Leadership & Web Lead',
    bio: 'Ketua kelas XI TKJ 3. Mengkoordinasikan proyek laboratorium jaringan, web profil kelas, dan kegiatan praktikum komputer.',
    skills: 'Project Leadership, Next.js, Linux Administration, Web Security',
    hobbies: 'Coding, Kepemimpinan, Membaca Jurnal IT',
    dream: 'Tech Startup Founder / CTO',
    photo: 'hamizan.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 23,
    full_name: 'Muhammad Kemal Faza',
    nickname: 'Kemal',
    class: 'XI TKJ 3',
    major: 'Blue Teaming & SOC Analysis',
    bio: 'Fokus pada analisis log keamanan SIEM, pencegahan ancaman cyber, monitoring firewall, dan respon insiden jaringan.',
    skills: 'SIEM Logging, Splunk Basics, Linux Security, Firewall Monitoring',
    hobbies: 'Security Labs, Gaming, Membaca Komik',
    dream: 'SOC Analyst Level 2',
    photo: 'kemal.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 24,
    full_name: 'Muhammad Rifqi Nasywan Athallah',
    nickname: 'Rifqi',
    class: 'XI TKJ 3',
    major: 'Network Automation & Python',
    bio: 'Mengembangkan skrip Python (Netmiko/Paramiko) untuk mengotomatisasi provisi perangkat perutean Cisco dan MikroTik.',
    skills: 'Python Netmiko, Paramiko, Cisco Automation, Linux',
    hobbies: 'Robotika, Coding Python, Catur',
    dream: 'Network Automation Architect',
    photo: 'rifqi.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 25,
    full_name: 'Nazriel Abiy Putra Veangga',
    nickname: 'Nazriel',
    class: 'XI TKJ 3',
    major: 'Web App & Database Security',
    bio: 'Bekerja pada penggabungan struktur basis data MariaDB dengan kerangka kerja aplikasi web modern Next.js.',
    skills: 'MariaDB, JavaScript, HTML5/CSS3, Git Version Control',
    hobbies: 'Video Editing, Coding, Futsal',
    dream: 'Fullstack Software Architect',
    photo: 'nazriel.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 26,
    full_name: 'Nizar Zulmi Firmansyah',
    nickname: 'Nizar',
    class: 'XI TKJ 3',
    major: 'Wireless Network Infrastructure',
    bio: 'Spesialis dalam merancang jangkauan Wi-Fi kampus/sekolah menggunakan sistem Ubiquiti UniFi dan CAPsMAN MikroTik.',
    skills: 'Ubiquiti UniFi, MikroTik Wireless, CAPsMAN, IP Subnetting',
    hobbies: 'Sepakbola, Outdoor Activity, Kopi',
    dream: 'Telecommunications Network Engineer',
    photo: 'nizar.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 27,
    full_name: 'Radine Dygtastya Rahmadhani',
    nickname: 'Radine',
    class: 'XI TKJ 3',
    major: 'IT Quality Assurance & Web Testing',
    bio: 'Menguji kualitas fungsional dan keamanan setiap rilis modul aplikasi web profil siswa XI TKJ 3.',
    skills: 'Web Audit, Security QA, HTML/CSS, Manual Testing',
    hobbies: 'Berenang, Membaca, Music',
    dream: 'QA Security Auditor',
    photo: 'radine.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 28,
    full_name: 'Rahel Maryam',
    nickname: 'Rahel',
    class: 'XI TKJ 3',
    major: 'Web Security & Tech Documentation',
    bio: 'Menyusun dokumentasi lengkap analisis kerentanan SQLi, XSS, dan Path Traversal untuk tugas praktikum keamanan web.',
    skills: 'Technical Writing, XSS Vulnerability Analysis, React, HTML/CSS',
    hobbies: 'Menulis, Fotografi, Desain',
    dream: 'Technical Product Manager',
    photo: 'rahel.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 29,
    full_name: 'Satria Banyu Seki',
    nickname: 'Satria',
    class: 'XI TKJ 3',
    major: 'Linux System Hardening & Security',
    bio: 'Memperkuat keandalan server Linux terhadap serangan brute-force, unauthorized access, IPTables, dan eksploitasi.',
    skills: 'Linux Hardening, SSH Keys & Tunneling, IPTables, Cryptography Basics',
    hobbies: 'Bela Diri, Gaming, Membaca',
    dream: 'Information Security Officer',
    photo: 'satria.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 30,
    full_name: 'Valvizzy Piscesio Lois',
    nickname: 'Valvizzy',
    class: 'XI TKJ 3',
    major: 'Network Routing & Protocol Tech',
    bio: 'Terampil melakukan penghitungan IP VLSM, IPv6 transition, Packet Tracer simulation, dan analisis alur paket jaringan.',
    skills: 'Packet Tracer Simulation, Subnetting VLSM, IPv6 Configuration, OSPF',
    hobbies: 'Produksi Musik, Gaming, Komputer',
    dream: 'NOC Engineer',
    photo: 'valvizzy.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 31,
    full_name: 'Yohan Alim Wijaya',
    nickname: 'Yohan',
    class: 'XI TKJ 3',
    major: 'Server Virtualization & Microservices',
    bio: 'Menguasai pembuatan kontainer Docker Engine, KVM Virtualization, dan isolasi layanan web aplikasi untuk siswa.',
    skills: 'Docker Engine, Linux Server, KVM Virtualization, Shell Automation',
    hobbies: 'PC Building, Hardware Modding, Membaca',
    dream: 'Infrastructure & Container Engineer',
    photo: 'yohan.jpg',
    created_at: new Date().toISOString()
  },
  {
    id: 32,
    full_name: 'Ziyadatul Ilman Nafiah',
    nickname: 'Ziyada',
    class: 'XI TKJ 3',
    major: 'Web Applications & MariaDB Integration',
    bio: 'Spesialis integrasi MariaDB dengan antarmuka web Next.js untuk penampilan data siswa secara dinamis dan responsif.',
    skills: 'MariaDB SQL, React, JavaScript, CSS Grid/Flexbox',
    hobbies: 'Membaca Jurnal, Coding, Traveling',
    dream: 'Database Systems Engineer',
    photo: 'ziyada.jpg',
    created_at: new Date().toISOString()
  }
];
